//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task : BaseModel
    {

        public Task()
        {
           
        }

        public Task(string taskName, string taskContent)
        {
            this.TaskName = taskName;
            this.TaskContent = taskContent;
        }




        public int Id { get; set; }

        private string _TaskName;        

        public string TaskName
        {
            get { return _TaskName; }
            set { _TaskName = value; OnPropertyChanged(); }
        }

        private string _TaskContent;

        public string TaskContent
        {
            get { return _TaskContent; }
            set { _TaskContent = value; OnPropertyChanged(); }
        }

        private Nullable<int> _CustomerId;

        
        public Nullable<int> CustomerId
        {
            get { return _CustomerId; }
            set { _CustomerId = value; OnPropertyChanged(); }
        }

            
        public virtual Customer Customer { get; set; }
    }
}
